### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by EspyskittUnlimited** [hecksadecimal/newerparp#8]
Not sure if I am doing this in the correct place but here goes. I have a beta key from the kickstarter and was trying to login and redeem my key. Kept saying my username or password was incorrect. Tried forgot my password but none of my emails worked, kept saying my email didn't exist. petersenkatey @gmail.com is the one I used for the kickstarter firestomstar@gmail.com is the email I used on old parp. One of the discord mods told me to make a ticket. Not sure if this is where I need to submit it.

**Comment by hecksadecimal** [comment]
This is not a site bug. For issues relating to accessing your account, join the [MxRP discord](https://discord.gg/msparp) and create a ticket in the ticket channel, or email [mxrphelpdesk@gmail.com](mailto:mxrphelpdesk@gmail.com).
