### ISSUE TITLE
scrollable wysiwyg options on mobile

### ISSUE THREAD

**Issue by amazingakita** [hecksadecimal/newerparp#9]
**Is your feature request related to a problem? Please describe.**
My phone is just narrow enough that the attachments button is not shown on the screen.
![SmartSelect_20231230_063224_Firefox Nightly](https://github.com/hecksadecimal/newerparp/assets/39305711/ea7ccdf6-0831-44fd-837f-47ca6f903343)
I can reach it by typing a long message, but that shifts the whole screen over, and I then lose the start of messages until I type a character & delete that.

https://github.com/hecksadecimal/newerparp/assets/39305711/4e3ced8c-26ba-49fe-959a-5bf1fbdd8697

**Describe the solution you'd like**
a horizontal scroll bar so I can move the options left/right without having to type a long message 

**Describe alternatives you've considered**
wrapping the options, so they hit two lines on narrower screens. this would make it more obvious to users that there is in fact other options out there than the scroll bar, although it would fill up more of the small screen space for mobile users

**Additional context**
for testing purposes, my screen resolution is 1080 x 2640 pixels

**Comment by hecksadecimal** [comment]
Give this a try now, tell me what you think.

**Comment by amazingakita** [comment]
wonderful, thank you!
![SmartSelect_20231230_175042_Firefox Nightly](https://github.com/hecksadecimal/newerparp/assets/39305711/6524f8ed-8a32-4bd2-a8be-3e9f13de1c22)

i especially like the smaller send button too
